import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/entities/loan_payment.dart';

/// Loan Payment Model for Firestore serialization
class LoanPaymentModel extends LoanPayment {
  const LoanPaymentModel({
    required super.id,
    required super.loanId,
    required super.amount,
    required super.paymentDate,
    super.walletId,
    super.note,
    super.isAutoGenerated,
  });

  factory LoanPaymentModel.fromSnapshot(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return LoanPaymentModel(
      id: doc.id,
      loanId: data['loanId'] ?? '',
      amount: (data['amount'] as num?)?.toDouble() ?? 0.0,
      paymentDate: (data['paymentDate'] as Timestamp).toDate(),
      walletId: data['walletId'],
      note: data['note'],
      isAutoGenerated: data['isAutoGenerated'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'loanId': loanId,
      'amount': amount,
      'paymentDate': Timestamp.fromDate(paymentDate),
      'walletId': walletId,
      'note': note,
      'isAutoGenerated': isAutoGenerated,
      'createdAt': FieldValue.serverTimestamp(),
    };
  }

  factory LoanPaymentModel.fromEntity(LoanPayment payment) {
    return LoanPaymentModel(
      id: payment.id,
      loanId: payment.loanId,
      amount: payment.amount,
      paymentDate: payment.paymentDate,
      walletId: payment.walletId,
      note: payment.note,
      isAutoGenerated: payment.isAutoGenerated,
    );
  }
}
