// File generated by user (via MCP data)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // Use iOS config for macOS if bundle IDs match, or Web if intended
        // Here we use iOS config as we registered com.finlisty.finlisty for iOS
        // and local macOS config uses the same bundle ID.
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kkhwk6kQHvVLaA_SJLT5p3v5bmaxvpo',
    appId: '1:297166576100:web:542eb23b7fb99e5dafcff1',
    messagingSenderId: '297166576100',
    projectId: 'finlisty-app-bd',
    authDomain: 'finlisty-app-bd.firebaseapp.com',
    storageBucket: 'finlisty-app-bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOpoSTILmZuWl8KVQV6sJPHHMQbKDmpow',
    appId: '1:297166576100:android:96b1081e3ddbaba1afcff1',
    messagingSenderId: '297166576100',
    projectId: 'finlisty-app-bd',
    storageBucket: 'finlisty-app-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4Xg_vQ8O45fXo140C7-olSRm_8k37Ew',
    appId: '1:297166576100:ios:19a9b24893043065afcff1',
    messagingSenderId: '297166576100',
    projectId: 'finlisty-app-bd',
    storageBucket: 'finlisty-app-bd.firebasestorage.app',
    iosBundleId: 'com.finlisty.finlisty',
  );
}
