import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../../domain/entities/wallet.dart';
import '../../domain/repositories/wallet_repository.dart';
import '../datasources/wallet_remote_data_source.dart';
import '../models/wallet_model.dart';

class WalletRepositoryImpl implements WalletRepository {
  final WalletRemoteDataSource remoteDataSource;

  WalletRepositoryImpl({required this.remoteDataSource});

  @override
  Future<Either<Failure, List<Wallet>>> getWallets() async {
    try {
      final remoteWallets = await remoteDataSource.getWallets();
      return Right(remoteWallets);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Stream<List<Wallet>> getWalletsStream() {
    return remoteDataSource.getWalletsStream();
  }

  @override
  Future<Either<Failure, void>> addWallet(Wallet wallet) async {
    try {
      final walletModel = WalletModel(
        id: '', // ID generated by Firestore
        name: wallet.name,
        type: wallet.type,
        balance: wallet.balance,
        color: wallet.color,
        isArchived: wallet.isArchived,
      );
      await remoteDataSource.addWallet(walletModel);
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> updateWallet(Wallet wallet) async {
    try {
       final walletModel = WalletModel(
        id: wallet.id, 
        name: wallet.name,
        type: wallet.type,
        balance: wallet.balance,
        color: wallet.color,
        isArchived: wallet.isArchived,
      );
      await remoteDataSource.updateWallet(walletModel);
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }
}
