import 'package:equatable/equatable.dart';

/// Loan Payment entity for tracking partial and full payments
/// Per PRD: Maintain payment history for loans
class LoanPayment extends Equatable {
  final String id;
  final String loanId;
  final double amount;
  final DateTime paymentDate;
  final String? walletId;
  final String? note;
  final bool isAutoGenerated; // For recurring payments

  const LoanPayment({
    required this.id,
    required this.loanId,
    required this.amount,
    required this.paymentDate,
    this.walletId,
    this.note,
    this.isAutoGenerated = false,
  });

  @override
  List<Object?> get props => [
        id,
        loanId,
        amount,
        paymentDate,
        walletId,
        note,
        isAutoGenerated,
      ];
}
