import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../../domain/entities/loan.dart';
import '../../domain/repositories/loan_repository.dart';
import '../datasources/loan_remote_data_source.dart';
import '../models/loan_model.dart';

class LoanRepositoryImpl implements LoanRepository {
  final LoanRemoteDataSource remoteDataSource;

  LoanRepositoryImpl({required this.remoteDataSource});

  @override
  Future<Either<Failure, void>> addLoan(Loan loan) async {
    try {
      final model = LoanModel(
        id: '', // Generated by Firestore
        personName: loan.personName,
        type: loan.type,
        principalAmount: loan.principalAmount,
        outstandingAmount: loan.outstandingAmount,
        interestRate: loan.interestRate,
        startDate: loan.startDate,
        dueDate: loan.dueDate,
        status: loan.status,
        linkedWalletId: loan.linkedWalletId,
      );
      await remoteDataSource.addLoan(model);
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Stream<List<Loan>> getLoansStream() {
    return remoteDataSource.getLoansStream();
  }

  @override
  Future<Either<Failure, void>> repayLoan(String loanId, double amount, String walletId, bool isLoanGiven) async {
    try {
      await remoteDataSource.repayLoan(loanId, amount, walletId, isLoanGiven);
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }
}
