import 'package:flutter/material.dart';
import '../../../../config/theme/app_colors.dart';
import '../../../../injection_container.dart';
import '../../domain/entities/loan.dart';
import '../../domain/repositories/loan_repository.dart';

class AddLoanPage extends StatefulWidget {
  const AddLoanPage({super.key});

  @override
  State<AddLoanPage> createState() => _AddLoanPageState();
}

class _AddLoanPageState extends State<AddLoanPage> {
  LoanType _type = LoanType.given;
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _amountController = TextEditingController();
  final TextEditingController _interestController = TextEditingController();
  DateTime _startDate = DateTime.now();
  DateTime? _dueDate;
  
  bool _isLoading = false;

  Future<void> _saveLoan() async {
    if (_nameController.text.isEmpty || _amountController.text.isEmpty) return;

    setState(() => _isLoading = true);

    final amount = double.tryParse(_amountController.text) ?? 0.0;
    final interest = double.tryParse(_interestController.text);

    final loan = Loan(
      id: '', // Generated by Repo/Firestore
      personName: _nameController.text,
      type: _type,
      principalAmount: amount,
      outstandingAmount: amount, // Start with full amount
      interestRate: interest,
      startDate: _startDate,
      dueDate: _dueDate,
      status: LoanStatus.active,
    );

    final result = await sl<LoanRepository>().addLoan(loan);

    setState(() => _isLoading = false);

    if (mounted) {
      result.fold(
        (l) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(l.message))),
        (r) => Navigator.pop(context),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Add Loan / Debt")),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            // Segmented Control
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(4),
              decoration: BoxDecoration(
                color: Colors.grey.shade100,
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                children: [
                   Expanded(child: _buildSegment("Start Giving", LoanType.given)),
                   Expanded(child: _buildSegment("Start Borrowing", LoanType.taken)),
                ],
              ),
            ),
            const SizedBox(height: 32),

            TextField(
              controller: _nameController,
              decoration: const InputDecoration(labelText: "Person Name", hintText: "e.g. Rahim"),
            ),
            const SizedBox(height: 16),
            
            TextField(
              controller: _amountController,
              keyboardType: TextInputType.number,
              decoration: const InputDecoration(labelText: "Amount", prefixText: "৳ "),
            ),
            const SizedBox(height: 16),

            Row(
              children: [
                Expanded(
                  child: GestureDetector(
                    onTap: () async {
                      final d = await showDatePicker(
                        context: context, 
                        initialDate: _startDate, 
                        firstDate: DateTime(2020), 
                        lastDate: DateTime(2030)
                      );
                      if (d != null) setState(() => _startDate = d);
                    },
                    child: InputDecorator(
                      decoration: const InputDecoration(labelText: "Start Date"),
                      child: Text("${_startDate.toLocal()}".split(' ')[0]),
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: GestureDetector(
                    onTap: () async {
                      final d = await showDatePicker(
                        context: context, 
                        initialDate: _startDate.add(const Duration(days: 30)), 
                        firstDate: _startDate, 
                        lastDate: DateTime(2030)
                      );
                      if (d != null) setState(() => _dueDate = d);
                    },
                    child: InputDecorator(
                      decoration: const InputDecoration(labelText: "Due Date (Opt)"),
                      child: Text(_dueDate != null ? "${_dueDate!.toLocal()}".split(' ')[0] : "Select"),
                    ),
                  ),
                ),
              ],
            ),
             const SizedBox(height: 16),
            
             TextField(
              controller: _interestController,
              keyboardType: TextInputType.number,
              decoration: const InputDecoration(labelText: "Interest Rate % (Optional)", suffixText: "%"),
            ),

            const SizedBox(height: 32),
            SizedBox(
              width: double.infinity,
              height: 56,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _saveLoan,
                style: ElevatedButton.styleFrom(
                  backgroundColor: _type == LoanType.given ? AppColors.income : AppColors.expense,
                ),
                child: _isLoading 
                    ? const CircularProgressIndicator(color: Colors.white) 
                    : Text(
                        _type == LoanType.given ? "LEND MONEY" : "BORROW MONEY",
                        style: const TextStyle(fontWeight: FontWeight.bold),
                      ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSegment(String title, LoanType type) {
    final isSelected = _type == type;
    final color = type == LoanType.given ? AppColors.income : AppColors.expense;
    
    return GestureDetector(
      onTap: () => setState(() => _type = type),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          color: isSelected ? color : Colors.transparent,
          borderRadius: BorderRadius.circular(10),
        ),
        child: Text(
          title,
          textAlign: TextAlign.center,
          style: TextStyle(
            color: isSelected ? Colors.white : Colors.grey.shade600,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
    );
  }
}
